# Configure Zabbix Proxy
- name: Configure Zabbix Proxy
  tags: zabbix-proxy
  template:
    src: zabbix_proxy.conf.j2
    dest: /etc/zabbix/zabbix_proxy.conf
    owner: root
    group: root
    mode: 0644

- name: Restart and enable Zabbix Proxy service
  tags: zabbix-proxy
  service:
    name: zabbix-proxy
    state: restarted
    enabled: yes
